version: '2.2'

services:
  postgres:
    image: postgres:12
    command: postgres -c 'max_connections=500'
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - "vol_postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
    networks:
      - rust_user_net
  rust_user-hw:
    depends_on:
      - postgres
    build: ../
    ports:
      - "8000:8000"
    environment:
      - "RUST_LOG=info"
      - "DATABASE_URL=postgres://admin:admin@postgres:5432/admin"
    networks:
      - rust_user_net

volumes:
  vol_postgres:

networks:
  rust_user_net:
    driver: bridge